# 3 контрольная по дискретной математике
чето там про графы

## теорма Эрдеша- Галлаи  
разбиение $(d_1,..,d_n), d_1+..+d_n=2k$ - графическое в том и только том случае,когда:  
$$\sum_{i=1}^r d_i \le r(r-1) + \sum_{i=r+1}^{n} \min{(r,d_i)}$$ 
для всех $r \in [1,n-1]$ .  
$\sum_{i=r+1}^{n} \min{(r,d_i)}$ обозначим за `tmp`

In [35]:
# d = [5,5,3,3,2,2,2]
d = [3,3,3,1]
# d = [4,4,3,3,2,2,1,1]
# d = [7,6,3,3,2,2,1,1]
d= [5,5,4,4,4,3,3,3,3,2,2,2,1,1]
d = sorted(d, reverse=True)
n = len(d)

if sum(d)%2==0:
    print('summa chetnaya-OK')
else:
    print('summa nechetnaya- NOT OK')

for r in range(1,n):
    print('r={}'.format(r), end=' : ')
    tmp = 0
    for i in range(r+1,n+1):
        tmp += min(r, d[i-1])

    if sum(d[0:r]) <= r*(r-1) + tmp:
         print('ok')
    else:
        print('not ok')

d = np.array(d)


summa chetnaya-OK
r=1 : ok
r=2 : ok
r=3 : ok
r=4 : ok
r=5 : ok
r=6 : ok
r=7 : ok
r=8 : ok
r=9 : ok
r=10 : ok
r=11 : ok
r=12 : ok
r=13 : ok


## Алгоритм Гавела — Хакими
таким образом строим лесенку  
потом идем по ней снизу вверх и добавляя новые вершины строим граф  
*примечание:* лесенка строится до тех пор пока не станет простой либо не будет содержать отрицательные чиселки. В простом случае все ок - строим граф, если есть отрицательное число - увы, список валентностей не графический

In [79]:
d = [5,5,4,4,4,3,3,3,3,2,2,2,1,1]
d = [4,4,3,3,2,2,1,1]
d = np.sort(np.array(d))[::-1]
print(d)
while d[np.where(d<=0)].shape[0]==0 and d[np.where(d<=1)].shape[0]!=d.shape[0] :
    mask = np.hstack( (np.ones(d[0]), np.zeros(d[1:].shape[0] - d[0])) ).astype('int')
    d = d[1:] - mask 
    # print(d)
    d = np.sort(d)[::-1]
    print(d)

[4 4 3 3 2 2 1 1]
[3 2 2 2 1 1 1]
[1 1 1 1 1 1]
